version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d8:5d:11:5e:40:1d:23:29:ea:54:cd:a2:40:51:43:e8"
      - checkout
      - restore_cache:
          keys:
           - dependencies-
      - run:
          name: Install
          command: npm install
      -save-cache:
          path:
            - node_moudules
          key: dependencies-
      - run:
          name: Build github pages
          command: npm build         
      -run:
          name: gh-pages
          command: npm deploy